linters:
  disable-all: true
  enable:
    - errcheck
    - gci
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nilerr
    - prealloc
    - staticcheck
    - typecheck
    - unparam
    - unused
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(my-judgment)
